# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-27 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('dateField', models.DateField()),
                ('timeField', models.TimeField()),
                ('status', models.CharField(max_length=15)),
            ],
        ),
    ]
